vim.g.enfocado_style = 'neon'

-- " NOTE: To see a list of all available plugins, run
-- " `:h enfocado-colorscheme` at the vim commandline.
-- vim.g.enfocado_plugins = [
--   \   'aerial',
--   \   'bufferline',
--   \   'cmp',
--   \   'dap-ui',
--   \   'gitsigns',
--   \   'illuminate',
--   \   'indent-blankline',
--   \   'lazy',
--   \   'lspconfig',
--   \   'matchup',
--   \   'neo-tree',
--   \   'noice',
--   \   'null-ls',
--   \   'smoothcursor',
--   \   'substitute',
--   \   'surround',
--   \   'telescope',
--   \   'treesitter',
--   \   'ts-rainbow2',
--   \   'visual-multi',
--   \   'yanky'
--   \ ]